apps/accounts/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #path("test/", views.test_view, name='test'),    
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

apps/products/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
]


#htmx specific url patterns
urlpatterns += [
    path('product_list/<int:cat_id>/', views.ProductListByCategory.as_view(), name='product_list_by_cat'),
    path('product_search/', views.ProductSearchView.as_view(), name='product_search'),    
    
    
    #stats
    
    path('stats/', views.StatsView.as_view(), name='stats'),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


#from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.products.urls')),
    path('payments/', include('apps.payments.urls')),
    
    path('__debug__/', include('debug_toolbar.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
)



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/theme/templates/includes/header.html
{% load i18n %}

<!-- header -->

<div class="flex justify-between items-center">
    <div class="space-y-2 w-1/2" >
        <h1 class="text-xl font-bold" >{% translate 'Welcome' %}, {{ request.user.username }}</h1>
        <p  class="font-light">
            {% if request.user.is_authenticated %}
                {% translate 'Your account type ' %}: {% if request.user.is_cashier %}{% translate 'Cashier' %}{% else %}{% translate 'Moderator' %}{% endif %}
            {% else %}
                {% translate 'You are not logged in' %}
            {% endif %}
        </p>
    </div>
    <div class="w-1/2" >
        
    <form  hx-post="{% url 'products:product_search' %}"
        hx-target="#product_list"
        hx-trigger="click"
        hx-swap="outerHTML" > 

        <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
        <div class="relative">
            <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                <svg aria-hidden="true" class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
            </div>
            {% csrf_token %}
            <input
                    name="search_text"


            type="search" id="default-search" class="block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500" placeholder="{% translate 'Search items' %}">
            <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-primary hover:bg-orange-400 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2">{% translate 'Search' %}</button>
        </div>
    </form>

    </div>
</div>

<!-- end header -->

apps/theme/templates/includes/left_menu.html
{% load i18n %}

{% with request.resolver_match.url_name as url_name %}

<!-- left menu -->
<div class="flex flex-col items-center justify-between h-full bg-white" >

    <div>

        <!-- logo -->
        <div class="p-5 border-slate-100" >
            <a class="text-primary text-2xl text-center uppercase font-bold" href="">
                JDI
            </a>
        </div>
        <!-- end logo -->


        <div class="flex flex-col items-center text-gray-400" >
            <a href="{% url 'products:product_list' %}" class="p-6 border-r-4 bg-customLighterGray {% if url_name == 'product_list' %} text-primary border-r-primary {% endif %} hover:duration-150 hover:duration-150" >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                </svg>
            </a>
            <a href="{% url 'products:stats' %}" class="{% if url_name == 'stats' %} text-primary border-r-primary {% endif %} p-6 border-r-4 hover:border-r-4 duration-150 hover:bg-customLighterGray hover:border-r-primary hover:text-primary hover:duration-150" >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z" />
                </svg>
            </a>
        </div>
    </div>


    <!-- login menu -->

    <div class="flex flex-col items-center text-gray-400" >

        <!-- langs -->
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as langs %}
        
        {% for lang in langs %}

            <a href="/{{lang.code}}" class="p-6" >
                {{lang.code}}
            </a>

        {% endfor %}

        {% if request.user.is_authenticated %}

        <a href="{% url 'accounts:logout' %}" class="p-6" >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
              </svg>
        </a>

        {% else %}

        <a href="{% url 'accounts:login' %}" class="p-6" >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                </svg>
        </a>

        {% endif %}
    </div>

    <!-- end login menu -->


</div>

<!-- end left menu -->

{% endwith %}