apps/payments/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'payments'

urlpatterns = [
    path('save_orders/', views.OrdersSaveView.as_view(), name='orders_save'),
    path('inovice_generate/<int:order_id>/', views.InoviceGenerateView.as_view(), name='inovice_generate')
]

apps/products/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
]


#htmx specific url patterns
urlpatterns += [
    path('product_list/<int:cat_id>/', views.ProductListByCategory.as_view(), name='product_list_by_cat'),
    path('product_search/', views.ProductSearchView.as_view(), name='product_search'),    
    
    
    #stats
    
    path('stats/', views.StatsView.as_view(), name='stats'),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


#from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.products.urls')),
    path('payments/', include('apps.payments.urls')),
    
    path('__debug__/', include('debug_toolbar.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
)



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/products/models.py
from datetime import date
from django.utils import timezone

from django.db import models
from django.utils.translation import gettext as _
from django.core.validators import MaxValueValidator, MinValueValidator

from core.models import TimeStampedModel



class Category(TimeStampedModel):
    name = models.CharField(_('Name'), max_length=30)
    description = models.CharField(_('Description'), max_length=100)
    
    
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'categories'

class Brand(TimeStampedModel):
    name = models.CharField(_('Name'), max_length=30)
    description = models.CharField(_('Description'), max_length=100)

    def __str__(self):
        return self.name
    

class Vendor(TimeStampedModel):
    first_name = models.CharField(_('First name'), max_length=30)
    last_name = models.CharField(_('Last name'), max_length=30)
    phone_number = models.CharField(_('Phone number'), max_length=15)
    
    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def __str__(self):
        return self.get_full_name()
    
    

class Product(TimeStampedModel):
    
    
    sku = models.CharField(_('Stock keeping unit'), max_length=8, unique=True, null=True, blank=True, db_index=True)
    name = models.CharField(_('Name'), max_length=30)
    
    description = models.CharField(_('Description'), max_length=100)
    price = models.DecimalField(_('Price'), max_digits=10, decimal_places=2)
    original_price = models.DecimalField(_('Original Price'), max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(_('Available quantity'), default=1)
    
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, related_name='products', blank=True, null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT, related_name='products')
    
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    
    def get_image_url(self):
        return self.image.url
    
    def __str__(self):
        return self.name
    
    @property
    def discount_percent(self):
        discount = getattr(self, 'discount', None)
        if discount and not discount.expired():
            return discount.discount_percent
        return 0

    
    @property
    def current_price(self):
        return self.price - (self.price*self.discount_percent/100)
    
    



class Discount(TimeStampedModel):
    
    discount_percent = models.DecimalField(_('Discount percent'), max_digits=5, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(100)])
    
    product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name='discount')
    
    start_date = models.DateField(_('Start date'), default=timezone.now)
    end_date = models.DateField(_('Expiry date'), default=timezone.now)
    
    def expired(self):
        if self.end_date > date.today():
            return False
        return True
            
                

apps/products/views.py
from django.shortcuts import render
from django.views.generic import View
from django.db.models import Count
from django.utils.translation import gettext as _
from django.views.generic.base import TemplateResponseMixin
from django.db.models import Sum
from django.contrib.auth.mixins import LoginRequiredMixin
import plotly.express as px
import pandas as pd


from .models import Product, Category, Brand
from ..payments.models import Order, OrderItem


class ProductListView(TemplateResponseMixin, View):
    
    template_name = 'products/list.html'
    
    def get(self, request):
        products = Product.objects.filter(quantity__gte=1)
        categories = Category.objects.annotate(num_products=Count('products')).filter(num_products__gte=1)
        brands = Brand.objects.annotate(num_products=Count('products')).filter(num_products__gte=1)        
        return self.render_to_response({
            'products': products,
            'categories': categories,
            'brands': brands,
        })



#htmx

class ProductListByCategory(TemplateResponseMixin, View):
    
    template_name = 'products/fragments/product_list.html'
    
    def get(self, request, cat_id):
        products = Product.objects.filter(category__id=cat_id)
        return self.render_to_response({
            'products': products,
        })
        
        
class ProductSearchView(TemplateResponseMixin, View):
    template_name = 'products/fragments/product_list.html'

    def post(self, request):
        search_text = request.POST.get('search_text')
        products = Product.objects.filter(quantity__gte=1, name__icontains=search_text)
        
        return self.render_to_response({
            'products': products,
        })


class StatsView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'products/stats/stats.html'
    
    
    
    def get(self, request):
        config = {'displayModeBar': False}
        
        orders = Order.objects.all()
        
        nb_of_sales_per_qt_qs = Category.objects.prefetch_related('products').annotate(
            number_of_sales=Sum('products__order_items__quantity')
        )
        
        nb_of_sales_per_qt_df = pd.DataFrame(list(nb_of_sales_per_qt_qs.values('name', 'number_of_sales')))
                
        revenues_per_date_df = pd.DataFrame({
            'date': [o.created.date() for o in orders],
            'profit': [o.total_profit for o in orders],
        })
        
        # example to test chart
        # revenues_per_date_df = pd.DataFrame({
        #     'date': [
        #         '2022-08-22',
        #         '2022-08-23',
        #         '2022-08-24',
        #         '2022-08-25',
        #         '2022-08-26',
        #         '2022-08-27',
        #         '2022-08-28',
        #         '2022-08-29'  
        #     ],
        #     'profit': [8541, 7514, 9850, 6352, 9851, 5362, 4041, 4520]
        # })
        
        
        revenues_per_date_df = revenues_per_date_df.groupby('date', as_index=False).agg(
            {'profit': 'sum'}
        )
        
        rev_per_date_fig = px.line(revenues_per_date_df,
            x = 'date',
            y = 'profit',
            title=_("Revenues per date."),
            labels= {
                'date': _('date'),
                'profit': _('profit'),
            }
        )

        nb_of_sales_per_qt_fig = px.pie(nb_of_sales_per_qt_df,
            values = 'number_of_sales',
            names = 'name',
            title = _('Number of sales per category.'),
            labels={
                'number_of_sales': _('number of sales'),
                'name': _('category name'),
            }                           
        )

        
        revenues_per_date_chart = rev_per_date_fig.to_html(config=config)
        nb_of_sales_per_qt_chart = nb_of_sales_per_qt_fig.to_html(config=config)
        
        return self.render_to_response({
            'revenues_per_date_chart': revenues_per_date_chart,
            'nb_of_sales_per_qt_chart': nb_of_sales_per_qt_chart,
        })

apps/theme/templates/products/list.html
{% extends '_base.html' %}
{% load i18n %}

{% block title %} {% translate 'Products' %} {% endblock %}


{% block content %}

<div x-data="{orders: [], total: 0}" class="flex justify-between w-full" id="product-page">
    <div class="m-5 w-2/3" >
        {% include 'includes/header.html' %}
        
    


        <!-- categories section -->
    
    
            <div class="flex align-items justify-start space-x-2 mt-8" >
                {% for category in categories %}
    
                    <button hx-get="{% url 'products:product_list_by_cat' category.id %}"
                        hx-trigger="click"
                        hx-target="#product_list"
                        hx-swap="outerHTML"
                    class="py-2 text-center bg-white px-10 rounded hover:bg-primary hover:duration-150 hover:text-white" >
                        <span class="font-light" >{{ category.name }}</span>
                    </button>
    
                {% endfor %}
            </div>
    
    
        <!-- end categories section -->
    
    
    
    
        <!-- products section -->

            {% include 'products/fragments/product_list.html' %}

        <!-- end products section -->
    
    </div>
    
    
    <form method="POST" action="{% url 'payments:orders_save' %}" class="h-full bg-white w-1/3 flex flex-col justify-between">
        {% csrf_token %}
        <div id="orders" class="m-5" >
            <h1 class="text-xl font-bold flex items-center justify-center mb-8" >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                  </svg>
                  Orders
            </h1>
    
                    <!-- orders -->
                    <!-- one order -->
                    <template  x-for="order in orders"  :key="order.item_id">
                        <div class="py-2 px-1 mb-2" >
                            <div class="flex justify-start items-center gap-2" >
                                <img class="w-16 h-16 rounded-md" :src="order.image_url" :alt="order.name">
                            <div class="space-y-2 w-full" >
                                <h4 x-text="order.name" class="font-bold" ></h4>
                                <div class="flex items-center justify-between" >
                                    <span x-text="'MAD ' + order.qt*order.current_price" class="text-primary" ></span>
                                    <div x-data class="flex justify-end" >
                                        <input type="button" value="+" @click="order.qt++;total+=1*order.current_price" class="py-1 rounded px-3 text-xl bg-primary text-white" >
                                        <input :name="'qt_item_' + order.item_id" class="w-16 text-center border-transparent focus:border-transparent focus:ring-0" type="text" pattern="^[1-9]\d*$" class="mx-4"  x-model="order.qt" >
                                        <input type="button" value="-" @click="order.qt--;total-=1*order.current_price" class="py-1 rounded px-3 text-xl bg-lighterPrimary text-white" >
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                    </template>
                    <!-- end one order -->

                <!-- end orders -->
                                
                    
        </div>


        <div class="m-4 space-y-4" >
            <!-- total current_prices section -->
            <div class="bg-gray-100 p-4 rounded text-center " >
                <h3 class="font-bold uppercase text-2xl" >{% translate 'Total in MAD' %}</h3>
                <span class="text-2xl" >MAD</span>
                <span class="text-2xl" x-text="total"></span> 
                
            </div>
            <!-- end total current_prices section -->

            <div>
                <button class="bg-primary text-white font-bold w-full p-4 rounded-lg" >
                    {% translate 'Pay & Generate novice' %}
                </button>
            </div>
                        
        </div>

    </form>
    
</div>

{% endblock %}

{% block extra_js %}

<script src="https://unpkg.com/htmx.org@1.8.0"></script>

{% endblock %}